Feature dao db
victorhausen/marketplace-dupla pull request #13
Opened 2021-01-11 19:30 UTC by ThiagoFiorelli

### Create
- arquivo no dao para criação e listagem de marketplace pelo banco de dados.
- arquivo no dao para criação e listagem de produtos pelo banco de dados.
- arquivo no dao para criação e listagem de logs pelo banco de dados.

### Update
- remodelado geração de logs, alterando as chamadas das funções do arquivo web.py para os arquivos nas pastas dao.

2021-01-11 19:43 UTC, Marcellort requested changes

2021-01-11 19:43 UTC, Marcellort commented on frontend/templates/list_log.html
>      </tr>
a tr aqui esta fechando se não me engano e acho que é nescessario identar tipo thead ae um tab e ae sim a abertura da tr

2021-01-11 19:52 UTC, Marcellort approved these changes

2021-01-12 11:53 UTC, victorhausen approved these changes
lgtm

2021-01-12 12:40 UTC, clara-odebrecht requested changes

2021-01-12 12:40 UTC, clara-odebrecht commented on backend/dao_db/product_dao_db.py
> +def get_products() -> None:
Ele retorna uma lista

2021-01-12 12:40 UTC, clara-odebrecht commented on backend/dao_txt/log_dao_txt.py
>  def list_logs()-> None:
Retorna lista

2021-01-12 12:40 UTC, clara-odebrecht commented on backend/dao_txt/marketplace_dao_txt.py
>  def get_marketplaces() -> None:
Retorna liiistaa

2021-01-12 12:40 UTC, clara-odebrecht commented on backend/dao_txt/product_dao_txt.py
>  def get_products()-> None:
.

2021-01-12 12:40 UTC, clara-odebrecht commented on backend/dao_db/marketplace_dao_db.py
> +def get_marketplaces() -> None:
Retorna lista

2021-01-12 12:40 UTC, clara-odebrecht commented on backend/dao_db/log_dao_db.py
> +def list_logs() -> None:
Retorna lista

2021-01-12 13:22 UTC, clara-odebrecht approved these changes

2021-01-12 13:55 UTC, quesiasts approved these changes

2021-01-12 14:17 UTC, merged